class BedrockType:
    UNCONNECTED_PING = 0x01
    UNCONNECTED_PONG = 0x1c
    SERVER_HANDSHAKE = 0x04
    CLIENT_HANDSHAKE = 0x03
    CLIENT_TESTCONNECTION1 = 0x05
    CLIENT_TESTCONNECTION1Reply = 0x06
    INCOMPATIBLE_RANKETPROTOCOL_VERSION = 0x19
    CLIENT_OPENCONNECTION = 0x07
    CLIENT_OPENCONNECTIONREPLY = 0x08